<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInitedbd0271403483e32ddd82b574df2af1
{
    public static $prefixLengthsPsr4 = array (
        'P' => 
        array (
            'PHPMailer\\PHPMailer\\' => 20,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'PHPMailer\\PHPMailer\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpmailer/phpmailer/src',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInitedbd0271403483e32ddd82b574df2af1::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInitedbd0271403483e32ddd82b574df2af1::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInitedbd0271403483e32ddd82b574df2af1::$classMap;

        }, null, ClassLoader::class);
    }
}
